site_name: IdeaWeaver Documentation
site_description: Documentation for IdeaWeaver - AI Model Training and Deployment Platform
site_author: IdeaWeaver Team
repo_url: https://github.com/yourusername/ideaweaver
repo_name: IdeaWeaver

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Training: training/training.md
    - Model Registry:
      - Overview: training/model-registry.md
      - MLflow: training/mlflow-registry.md
      - DagsHub: training/dagshub-registry.md
      - Comet: training/comet-registry.md
      - Hugging Face: training/huggingface-registry.md
      - AWS Bedrock: training/bedrock-registry.md
    - Evaluation: evaluation.md
    - Deployment: deployment.md
  - MCP:
    - Overview: mcp/mcp.md
    - AWS Integration: mcp/aws.md
    - Terraform Integration: mcp/terraform.md
  - Community:
    - Guidelines: community/guidelines.md
    - Roadmap: community/roadmap.md
  - API Reference:
    - Python API: api/python.md
    - REST API: api/rest.md
    - CLI Reference: api/cli.md
  - Contributing:
    - Development Guide: contributing/development.md
    - Code Style: contributing/code-style.md
    - Testing: contributing/testing.md
    - Documentation: contributing/documentation.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - FAQ: troubleshooting/faq.md
    - Support: troubleshooting/support.md
