site_name: IdeaWeaver Documentation
site_description: Documentation for IdeaWeaver - AI Model Training and Deployment Platform
site_author: IdeaWeaver Team
repo_url: https://github.com/yourusername/ideaweaver
repo_name: IdeaWeaver

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - Agent:
    - Overview: agent/overview.md
    - Commands: agent/commands.md
    - Examples: agent/examples.md
    - System_diagnostics: agent/SYSTEM_DIAGNOSTICS.md
  - RAG:
    - Overview: rag/overview.md
    - Commands: rag/commands.md
    - Evaluation: rag/evaluation.md
  - Fine-Tuning:
    - Overview: fine-tuning/overview.md
    - Commands: fine-tuning/commands.md
    - Fine-Tuning Methods: fine-tuning/fine-tuning-methods.md
    - Examples: fine-tuning/examples.md
  - Validation:
    - Overview: validation/overview.md
    - Commands: validation/commands.md
  - Training:
    - Train Output: training/train-output.md
    - MLflow: training/mlflow-registry.md
    - DagsHub: training/dagshub-registry.md
    - Comet: training/comet-registry.md
    - Hugging Face: training/huggingface-registry.md
    - AWS Bedrock: training/bedrock-registry.md
  - Model Registry:
    - MLflow: training/mlflow-registry.md
    - DagsHub: training/dagshub-registry.md
    - Comet: training/comet-registry.md
    - Hugging Face: training/huggingface-registry.md
    - AWS Bedrock: training/bedrock-registry.md
  - Evaluation:
    - Evaluation: evaluation/evaluation.md
  - MCP:
    - AWS Integration: mcp/aws.md
    - Terraform Integration: mcp/terraform.md
    - GitHub Integration: mcp/github.md
  - Docker:
    - Docker: docker/docker.md
  - Community:
    - Guidelines: community/guidelines.md
    - Roadmap: community/roadmap.md
  #- API Reference:
  #  - CLI Commands: reference/cli-commands.md
  - Contributing:
    - Contributing Guide: community/contributing.md
  - Troubleshooting:
    - Support: community/support.md
