site_name: IdeaWeaver Model Registry
site_description: A comprehensive CLI tool for AI model training, evaluation, and deployment
site_author: IdeaWeaver Team
site_url: https://github.com/ideaweaver-ai-code/ideaweaver

repo_name: ideaweaver-ai-code/ideaweaver
repo_url: https://github.com/ideaweaver-ai-code/ideaweaver
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/ideaweaver_logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Downloads:
    - Overview: downloads/overview.md
    - Commands: downloads/commands.md
  - Validation:
    - Overview: validation/overview.md
    - Commands: validation/commands.md
  #- Model Comparison:
  #  - Overview: comparison/overview.md
  #  - Commands: comparison/commands.md
  - RAG:
    - Overview: rag/overview.md
    - Commands: rag/commands.md
    - Evaluation: rag/evaluation.md
  - Training:
    - Training Output: training/train-output.md
  - Fine-tuning:
    - Overview: fine-tuning/overview.md
    - Commands: fine-tuning/commands.md
    - Examples: fine-tuning/examples.md
  - Agent:
    - Overview: agent/overview.md
    - Commands: agent/commands.md
  - MCP:
    - GitHub Integration: mcp/github.md
  - Evaluation:
    -  Evaluation: evaluation.md 
  #- Reference:
  #  - CLI Commands: reference/cli-commands.md
  - Community:
    - Contributing: community/contributing.md
    - Support: community/support.md
  #-  Langfuse Monitoring: langfuse.md
